ExpenseTracker/Models/ErrorViewModel.cs
using System;

namespace ExpenseTracker.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ExpenseTracker/Models/Expenses.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace BorrowLanded.Models
{
    public class Expenses
    {
        [Key]
        public int Id { get; set; }

        [Required]
        [DisplayName("Expense Name")]
        public string ExpenseName { get; set; }

        [DisplayName("Expense Type")]
        public string ExpenseType { get; set; }

        [Required]
        [Range(0.1, double.MaxValue, ErrorMessage = "Amount must be greater than 0")]
        public double Amount { get; set; }

    }
}

ExpenseTracker/Models/Item.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace BorrowLanded.Models
{
    public class Item
    {
        [Key]
        public int Id { get; set; }

        public string Borrower { get; set; }

        public string Lender { get; set; }

        [DisplayName("Item name")]
        public string ItemName { get; set; }


    }
}

ExpenseTracker/Controllers/AppointmentController.cs
using Microsoft.AspNetCore.Mvc;

namespace ExpenseTracker.Controllers
{
    public class AppointmentController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

ExpenseTracker/Controllers/ExpensesController.cs
using BorrowLanded.Data;
using BorrowLanded.Models;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;

namespace BorrowLanded.Controllers
{
    public class ExpensesController : Controller
    {
        private readonly ApplicationDBContext _db;

        public ExpensesController(ApplicationDBContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            IEnumerable<Expenses> objList = _db.Expenses;
            return View(objList);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public IActionResult Create(Expenses obj)
        {
            if (ModelState.IsValid)
            {
                _db.Add(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        //Post Delete

        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public IActionResult DeletePost(int? id)
        {
            var obj = _db.Expenses.Find(id);
            if (obj == null)
            {
                return NotFound();
            }
            else
            {
                _db.Remove(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }



        }

        //Get Delete
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();

            }
            var obj = _db.Expenses.Find(id);

            if (obj == null)
            {
                return NotFound();
            }
            return View(obj);



        }
    }
}

ExpenseTracker/Controllers/HomeController.cs
using ExpenseTracker.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace ExpenseTracker.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ExpenseTracker/Controllers/ItemController.cs
using BorrowLanded.Data;
using BorrowLanded.Models;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;

namespace BorrowLanded.Controllers
{
    public class ItemController : Controller
    {
        private readonly ApplicationDBContext _db;

        public ItemController(ApplicationDBContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            IEnumerable<Item> objList = _db.Item;
            return View(objList);
        }

        //GET- Create
        public IActionResult Create()
        {
            return View();
        }

        //POST-Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Item obj)
        {
            _db.Item.Add(obj);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

ExpenseTracker/Views/Expenses/Create.cshtml
@model BorrowLanded.Models.Expenses;


<h1 class="align-content-center">Create Expense</h1>

<div class="mt-3">

<form method="post" asp-action="Create">
<div asp-validation-summary="ModelOnly" class="text-danger"></div>	

<label asp-for="ExpenseName" class="mt-3"></label>
<input asp-for="ExpenseName" type="text" class="form-control mt-1" placeholder="Expense Name"/>
<span asp-validation-for="ExpenseName" class="text-danger d-block"></span>
<label asp-for="ExpenseType" class="mt-3"></label>
<input asp-for="ExpenseType" type="text" class="form-control form-control-solid mt-1" placeholder="Expense Type"/>
<label asp-for="Amount" class="mt-3"></label>
<input asp-for="Amount" type="number" step="0.1" class="form-control form-control-transparent mt-1" placeholder="Expense Amount"/>
<span asp-validation-for="Amount" class="text-danger  d-block"></span>

<button class="btn btn-primary btn-light mt-3" type="submit">Create</button>

</form>


</div>

ExpenseTracker/Views/Expenses/Delete.cshtml
@model BorrowLanded.Models.Expenses;


<h1 class="align-content-center">Delete Expense</h1>

<div class="mt-3">

<form method="post" asp-action="DeletePost">

	<input asp-for="Id" hidden />

<label asp-for="ExpenseName" class="mt-3"></label>
<input asp-for="ExpenseName" disabled type="text" class="form-control mt-1" placeholder="Expense Name"/>
<label asp-for="ExpenseType" class="mt-3"></label>
<input asp-for="ExpenseType" disabled type="text" class="form-control form-control-solid mt-1" placeholder="Expense Type"/>
<label asp-for="Amount" class="mt-3"></label>
<input asp-for="Amount" disabled type="number" step="0.1" class="form-control form-control-transparent mt-1" placeholder="Expense Amount"/>

<button class="btn btn-primary btn-danger mt-3" type="submit">Delete</button>
<button asp-action="Index" class="btn btn-primary btn-danger mt-3" >Back</button>

</form>


</div>

ExpenseTracker/Views/Expenses/Index.cshtml
@model IEnumerable<BorrowLanded.Models.Expenses>

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
    <h1 class="m-2">Expenses</h1>

    </div>
    <div class="col-6 text-right">
    <a asp-controller="Expenses" asp-action="Create" class="btn btn-primary">Create New Expense</a>

    </div>
    </div>
    
</div>

@if (Model.Count() > 0)
        {
            <table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Id</th>
      <th scope="col">Expense Name</th>
      <th scope="col">Expense Type</th>
      <th scope="col">Expense Amount</th>
      
    </tr>
  </thead>
  <tbody>

      @foreach(var item in Model){
     <tr>
      <th scope="row">@item.Id</th>
      <th scope="row">@item.ExpenseName</th>
      <th scope="row">@item.ExpenseType</th>
      <td scope="row">@item.Amount</td>
      <td scope="row">
           <a asp-controller="Expenses" asp-action="Update" asp-route-Id="@item.Id" class="btn btn-primary mx-1">Update</a>
           <a asp-controller="Expenses" asp-action="Delete" asp-route-Id="@item.Id" class="btn btn-danger" mx-1>Delete</a>
      </td>
      <td></td>
    </tr>
        

      }
    

  </tbody>
</table>

        }
        else{
            <h2>No items created yet</h2>
        }

ExpenseTracker/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ExpenseTracker/Views/Item/Create.cshtml
@model BorrowLanded.Models.Item;


<h1 class="align-content-center">Create Item</h1>

<div class="mt-3">

<form method="post" asp-action="Create">

<label asp-for="ItemName" class="mt-3"></label>
<input asp-for="ItemName" type="text" class="form-control mt-1" placeholder="Item Name"/>
<label asp-for="Borrower" class="mt-3"></label>
<input asp-for="Borrower" type="text" class="form-control form-control-solid mt-1" placeholder="Borrower"/>
<label asp-for="Lender" class="mt-3"></label>
<input asp-for="Lender" type="text" class="form-control form-control-transparent mt-1" placeholder="Lender"/>

<button class="btn btn-primary btn-light mt-3" type="submit">Create</button>
</form>


</div>

ExpenseTracker/Views/Item/Index.cshtml
@model IEnumerable<BorrowLanded.Models.Item>

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
    <h1 class="m-2">Items</h1>

    </div>
    <div class="col-6 text-right">
    <a asp-controller="Item" asp-action="Create" class="btn btn-primary">Create New Item</a>

    </div>
    </div>
    
</div>

@if (Model.Count() > 0)
        {
            <table class="table table-dark">
  <thead>
    <tr>
      <th scope="col">Id</th>
      <th scope="col">Item Name</th>
      <th scope="col">Borrower</th>
      <th scope="col">Lender</th>
      
    </tr>
  </thead>
  <tbody>

      @foreach(var item in Model){
     <tr>
      <th scope="row">@item.Id</th>
      <th scope="row">@item.ItemName</th>
      <td>@item.Borrower</td>
      <td>@item.Lender</td>
      <td></td>
    </tr>
        

      }
    

  </tbody>
</table>

        }
        else{
            <h2>No items created yet</h2>
        }

ExpenseTracker/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ExpenseTracker</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ExpenseTracker</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Item" asp-action="Index">Items</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Expenses" asp-action="Index">My Expenses</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - ExpenseTracker - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>